In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [15]:

import numpy as np
arr = np.arange(30, 71, 2)
print(arr)
print(arr.size)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
21


In [2]:
#dasgal2

In [7]:
import numpy as np

def f_to_c(F):
    return (F-32)*5/9
def c_to_f(C):
    return C*9/5+32

F = np.array([0, 12, 45.21, 34, 99.91, 32], dtype=float)

C = f_to_c(F)
C_rounded = np.round(C, 2) 

print("Фаренгейтийн градусын утгууд:", F)
print("Цельсийн градусын утгууд:", C_rounded)

Фаренгейтийн градусын утгууд: [ 0.   12.   45.21 34.   99.91 32.  ]
Цельсийн градусын утгууд: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [12]:
#dasgal3

In [2]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
y= x.reshape(3, 2)
z= x.reshape(2, 3)
print(x)
print(y)
print(z)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#dasgal4

In [12]:
import numpy as np
a = np.array ([ 97, 101, 105, 111, 117])
b = np.array ( ['a', 'e', 'i', 'o', 'u'])
mask = (a > 100) & (a < 110) 
result = b[mask]
print(result)

['e' 'i']


In [13]:
#dasgal5 

In [16]:
import numpy as np
a = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
bt = b.T 
c = np.dot(bt, a) 
print(bt)
print( c)

[[1 3 5 7]
 [2 4 6 8]]
[[118 134 150]
 [140 160 180]]


In [18]:
#dasgal6

In [19]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [20]:
import pandas as pd

s = pd.Series([1,2,3,4,5,6,7,8,9,5,3])

print("Mean:", s.mean())
print("Std:", s.std())  

Mean: 4.818181818181818
Std: 2.522624895547565


In [21]:
#dasgal7


In [14]:
import pandas as pd

s = pd.Series(['php', 'python', 'java', 'c#'])

result = s.apply(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print(result)

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


In [23]:
#dasgal 8


In [2]:
from pandas import DataFrame
import numpy as np

a = DataFrame(
    {
        'name':     ['Dorj', 'Khulan', 'Sergelen', 'Ganchimeg', 'Khaliun', 'Bolor', 'Anu', 'Tsetse', 'Purev', 'Zulaa'],
        'score':    [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify':  ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    },
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
)

print('Dasgal_1')
print(a.head(3))

print('Dasgal_2')
print(a[['name', 'score']])

print('Dasgal_3')
print(a[a['attempts'] > 2])

print('Dasgal_4')
print(a[a['score'].between(15, 20)])

print('Dasgal_5')
print(a.loc[['a', 'c', 'e', 'f'], ['name', 'score']])

Dasgal_1
       name  score  attempts qualify
a      Dorj   12.5         1     yes
b    Khulan    9.0         3      no
c  Sergelen   16.5         2     yes
Dasgal_2
        name  score
a       Dorj   12.5
b     Khulan    9.0
c   Sergelen   16.5
d  Ganchimeg    NaN
e    Khaliun    9.0
f      Bolor   20.0
g        Anu   14.5
h     Tsetse    NaN
i      Purev    8.0
j      Zulaa   19.0
Dasgal_3
        name  score  attempts qualify
b     Khulan    9.0         3      no
d  Ganchimeg    NaN         3      no
f      Bolor   20.0         3     yes
Dasgal_4
       name  score  attempts qualify
c  Sergelen   16.5         2     yes
f     Bolor   20.0         3     yes
j     Zulaa   19.0         1     yes
Dasgal_5
       name  score
a      Dorj   12.5
c  Sergelen   16.5
e   Khaliun    9.0
f     Bolor   20.0
